version: '3'

services:
  php:
    container_name: php
    hostname: symfony-php
    build: .
    restart: "no" # unless-stopped
    depends_on: 
      - mysql
    ports:
      - 7780:8000
    volumes:
      - ./:/app
    networks:
      - pont

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: "no" # unless-stopped
    volumes:
      - data_mysql_sy:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - pont

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: "no" # unless-stopped
    ports:
      - 7779:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - pont

networks:
  pont:

volumes:
  data_mysql_sy: